//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverInsuranceDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarID { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string StateNumber { get; set; }
        public string STSNumber { get; set; }
        public string PTSNumber { get; set; }
    }
}
