//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverInsuranceDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int DriverID { get; set; }
        public string Region { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string LicenseSeries { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseDateIssued { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportDateIssued { get; set; }
    }
}
