//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverInsuranceDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePolicies
    {
        public int PolicyID { get; set; }
        public string PolicyNumber { get; set; }
        public string InsuranceCompany { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string LicenseSeries { get; set; }
        public string StateNumber { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
